name: Sync Upstream
on:
  schedule:
    - cron: "0 * * * *" # Runs hourly
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge Upstream
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote add upstream https://github.com/pixincreate/PixeneOS.git
          git fetch upstream

          # Try to merge. If it fails due to the Renovate file, force-remove them.
          git merge upstream/main --allow-unrelated-histories -m "Auto-sync" || \
          (git rm --ignore-unmatch .github/workflows/renovate.yml renovate.json5 && git commit -m "Auto-resolve renovate conflict")

          git push origin main
